remove auto trigger

diff --git a/.github/workflows/09-functions.yaml b/.github/workflows/09-functions.yaml
--- a/.github/workflows/09-functions.yaml
+++ b/.github/workflows/09-functions.yaml
@@ -18,15 +18,15 @@ jobs:
       if: ${{!cancelled() && contains(github.event.pull_request.title, 'fix')}}
       run:
         echo "Iam a bug fix"
-    - name: sleep 20 seconds
-      run: sleep 20
-    - name: Failing step
-      run: exit 1
-    - name: I will be skipped
+    # - name: sleep 20 seconds
+    #   run: sleep 20
+    # - name: Failing step
+    #   run: exit 1
+    - name: I will be executed
       if: ${{success()}}
       run:
         echo "I will print if previous steps succeed."
-    - name: I will execute
+    - name: I will be skipped
       if: ${{failure()}}
       run:
         echo "I will print if any previous step fails."
