using tag

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -27,9 +27,9 @@ jobs:
         with: 
           node-version: ${{ matrix.node-version}}
 
-      - name: fail fast test
-        if: matrix.tag == 'experimental'
-        run: exit 1
+      # - name: fail fast test
+      #   if: matrix.tag == 'experimental'
+      #   run: exit 1
 
       - name: perform some test
         run: |
